# Generated by Django 4.0.6 on 2022-09-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title'], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
    ]
